springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRING_DOC_ENABLED:true}
    groups:
      enabled: true
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
    operations-sorter: alpha
    tags-sorter: alpha
    config-url: ${server.path}/v3/api-docs/swagger-config
    url: ${server.path}/v3/api-docs

common:
  rest:
    open-api:
      servers: ${OPEN_API_SERVER:http://localhost:8080,/}
  security:
    cors:
      allowed-origins: ${CORS_ORIGINS:http://localhost:8080}
      allowed-methods: ${CORS_METHODS:*}
      allowed-headers: ${CORS_HEADERS:*}
    path-matcher:
      permit-all-path-patterns:
        - /webjars/swagger-ui/**
        - /v3/api-docs/**
        - /swagger-resources/**
        - /webjars/**
        - /swagger-ui/**
        - /swagger-ui.html
        - /null/swagger-resources/**
        - /actuator/**
        - /mock/**
        - /api/v1/app/*/public/**
        - /api/v1/system/groups/**
        - /api/v1/app/permissions/**
      ignore-authorization:
        - /api/v1/auth/**
